### ISSUE TITLE
HALAR/LREG webpage 404 not found

### ISSUE THREAD

**Issue by congyang1996** [thomaskuestner/MoCoGUI#1]
Hi, thomas, when I goto the HALAR/LREG website supplied in the readme, it shows 404 not found. So, did you have the downloaded source code on this website? Could you share it with me? I am a student in university and want to learn it more deeply. Thank you!

**Comment by thomaskuestner** [comment]
Hi Cong Yang,
the HALAR/LREG is from Buerger et al.  "Hierarchical adaptive local affine registration for fast and robust respiratory motion estimation" (https://www.sciencedirect.com/science/article/pii/S1361841511000314)
I am not mainting the linked website and unfortunately I don't have access to the source code of HALAR/LREG. I would suggest to contact Andrew King who is still at KCL. Maybe he can send you the code.
Kind regards, 
Thomas

**Comment by congyang1996** [comment]
Thanks for your reply and appreciate your information about Andrew King. I will try it.
Best regards.
